apiVersion: management.cattle.io/v3
kind: Token
authProvider: local
current: false
description: mytoken
expired: false
expiresAt: ""
isDerived: true
lastUpdateTime: ""
metadata:
  generateName: token-
  labels:
    authn.management.cattle.io/token-userId: user-zvnsr
    cattle.io/creator: norman
  name: token-ci
ttl: 0
token: zfllcbdr4677rkj4hmlr8rsmljg87l7874882928khlfs2pmmcq7l5
userId: user-zvnsr
userPrincipal:
  displayName: Default Admin
  loginName: admin
  me: true
  metadata:
    creationTimestamp: null
    name: local://user-zvnsr
  principalType: user
  provider: local
